spring:
  datasource:
    url:                  jdbc:mysql://localhost:3306/${MYSQL_DB}?serverTimezone=UTC&useSSL=false
    username:           ${MYSQL_USERNAME}
    password:           ${MYSQL_PASSWORD}
    validation-query:   select 1
    testeWhileIdle:     true
  jpa:
    properties:
      hibernate:
        dialect:        org.hibernate.dialect.MySQL5Dialect




