spring:
  profiles:
    active:             default
    include:            dev
  jackson:
      default-property-inclusion: non_null
  main:
    banner-mode: off
  cache:
    jcache:
      config: ehcache.xml
      provider: org.ehcache.jsr107.EhcacheCachingProvider

logging:
  level:
    org:
      springframework:
        boot:           WARN
        cache:          DEBUG
      hibernate:        WARN
      apache:
        catalina:       WARN
      ehcache:          DEBUG

management:
  port:                 8081
  context-path:         /admin

server:
  context-path:         /api

endpoints:
  info:
    enabled:            true
    sensitive:          false
  shutdown:
    enabled:            true
    sensitive:          true

info:
  app:
    name:               Handson Spring Boot Application
    description:        Handson Spring Boot Application
    version:            0.1.1-SNAPSHOT
  developers:
      - name:               Antonel Ernest Pazargic
        email:              antonel.pazargic@gmail.com
      - name:               Irina Stan
        email:              irina.stan@gmail.com

---
spring:
  profiles:             default
  application:
    name:               Handson-SpringBoot
server:
  port:                 8080

---
spring:
  profiles:             dev
  # the datasource for the dev is h2 which is automatically configured by spring boot as soon as the h2 is in the classpath. Check the maven dependecies to see if it is.
  datasource:
    url:                jdbc:h2:mem:myDb;DB_CLOSE_ON_EXIT=FALSE
    username:           sa

---
spring:
  profiles:             prod
  datasource:
    url:                jdbc:mysql://localhost:3306/${MYSQL_DB}?serverTimezone=UTC&useSSL=false
    username:           ${MYSQL_USERNAME}
    password:           ${MYSQL_PASSWORD}
    validation-query:   select 1
    testeWhileIdle:     true
  jpa:
    properties:
      hibernate:
        dialect:        org.hibernate.dialect.MySQL5Dialect

